import { NextRequest, NextResponse } from "next/server";
import { generateFountainText } from "@/lib/guion-processor";
import type { GuionJSON, ExportFormat } from "@/lib/types";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { guionJSON, guionText, format, title } = body as {
      guionJSON?: GuionJSON;
      guionText?: string;
      format: ExportFormat;
      title: string;
    };

    const safeTitle = (title || "script").replace(/[^a-z0-9]/gi, "_");
    const timestamp = new Date().toISOString().split("T")[0];
    const filename = `${safeTitle}_${timestamp}`;

    switch (format) {
      case "fountain": {
        if (!guionJSON) {
          return NextResponse.json({ error: "guionJSON required for fountain export" }, { status: 400 });
        }
        const fountainText = generateFountainText(guionJSON);
        return new NextResponse(fountainText, {
          headers: {
            "Content-Type": "text/plain; charset=utf-8",
            "Content-Disposition": `attachment; filename="${filename}.fountain"`,
          },
        });
      }

      case "json": {
        if (!guionJSON) {
          return NextResponse.json({ error: "guionJSON required for JSON export" }, { status: 400 });
        }
        return new NextResponse(JSON.stringify(guionJSON, null, 2), {
          headers: {
            "Content-Type": "application/json",
            "Content-Disposition": `attachment; filename="${filename}.json"`,
          },
        });
      }

      case "markdown": {
        const mdContent = generateMarkdown(guionText || "", title, guionJSON);
        return new NextResponse(mdContent, {
          headers: {
            "Content-Type": "text/markdown; charset=utf-8",
            "Content-Disposition": `attachment; filename="${filename}.md"`,
          },
        });
      }

      case "pdf": {
        // PDF generation - return screenplay text for client-side rendering
        // Full PDF with pdfmake would be implemented here
        const textContent = guionText || (guionJSON ? "Screenplay content" : "");
        return NextResponse.json({
          success: true,
          message: "PDF generation - use client-side renderer",
          textContent,
          filename: `${filename}.pdf`,
        });
      }

      default:
        return NextResponse.json({ error: "Invalid format" }, { status: 400 });
    }
  } catch (error: any) {
    console.error("[/api/guion/export]", error);
    return NextResponse.json(
      { error: error.message || "Export failed" },
      { status: 500 }
    );
  }
}

function generateMarkdown(text: string, title: string, guionJSON?: GuionJSON): string {
  const lines: string[] = [];
  lines.push(`# ${title}`);
  lines.push(`*Generated by Script Bud — ${new Date().toLocaleDateString("es-ES")}*`);
  lines.push("");

  if (guionJSON?.metadata) {
    const m = guionJSON.metadata;
    lines.push("## Metadata");
    lines.push(`- **Género:** ${m.genre}`);
    lines.push(`- **Duración:** ${m.durationMinutes} minutos`);
    lines.push(`- **Estructura:** ${m.structure}`);
    lines.push(`- **Protagonista:** ${m.protagonist}`);
    lines.push(`- **Pregunta Central:** ${m.centralQuestion}`);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  lines.push("## Guion");
  lines.push("");
  lines.push("```");
  lines.push(text);
  lines.push("```");

  return lines.join("\n");
}
