// ─────────────────────────────────────────────────────────────
//  Script Bud — Guion Processor
//  Source: metaprompt_maestro_antigravity.md, PARTE 3.5-3.6
//  Converts between GuionJSON ↔ plaintext screenplay format
// ─────────────────────────────────────────────────────────────

import type { GuionJSON, Scene, DialogueLine } from "./types";

// ── Screenplay Text Generator ─────────────────────────────────
// Converts GuionJSON → Formatted screenplay text (Courier format implied)
export function generateScreenplayText(guion: GuionJSON): string {
  // Alias to generateFountainText so we don't force spaces
  return generateFountainText(guion);
}

// ── Fountain Format Generator ──────────────────────────────────
// Source: plan_investigacion_agente_guion_completo.md, TIER 5
// Compatible with Final Draft, Writerduty, WriterSolo
export function generateFountainText(guion: GuionJSON): string {
  const lines: string[] = [];

  // Fountain title page
  lines.push(`Title: ${guion.metadata.title}`);
  lines.push(`Credit: Written by`);
  lines.push(`Author: Script Bud`);
  lines.push(`Draft Date: ${new Date().toLocaleDateString("es-ES")}`);
  lines.push(`Contact: Generated by Script Bud`);
  lines.push("");
  lines.push("===");
  lines.push("");

  guion.scenes.forEach((scene) => {
    // Slugline (auto-detected by Fountain if ALL CAPS + INT./EXT.)
    lines.push(scene.slugline);
    lines.push("");

    // Action (plain text paragraphs)
    if (scene.action) {
      lines.push(scene.action);
      lines.push("");
    }

    // Dialogue
    if (scene.dialogue && scene.dialogue.length > 0) {
      scene.dialogue.forEach((line) => {
        lines.push(line.character);
        if (line.parenthetical) {
          lines.push(`(${line.parenthetical.replace(/[()]/g, "")})`);
        }
        lines.push(line.text);
        lines.push("");
      });
    }
  });

  return lines.join("\n");
}

// ── Screenplay Text Parser ─────────────────────────────────────
// Parses formatted screenplay text → partial Scene list
// (for sync from editor back to board)
export function parseScreenplayTextToScenes(text: string): Partial<Scene>[] {
  const scenes: Partial<Scene>[] = [];
  const sluglineRegex = /^(INT\.|EXT\.|I\/E\.)\s+.+\s+-\s+.+$/im;

  const blocks = text.split(/\n{2,}/);
  let currentScene: Partial<Scene> | null = null;
  let sceneCounter = 0;

  blocks.forEach((block) => {
    const trimmed = block.trim();

    if (sluglineRegex.test(trimmed)) {
      if (currentScene) {
        scenes.push(currentScene);
      }
      sceneCounter++;
      currentScene = {
        id: `SCN_${String(sceneCounter).padStart(3, "0")}`,
        sceneNumber: sceneCounter,
        slugline: trimmed,
        action: "",
        characters: [],
        dialogue: [],
        durationSeconds: 60, // default 1 min
      };
    } else if (currentScene) {
      if (!currentScene.action) {
        currentScene.action = trimmed;
      }
    }
  });

  if (currentScene) {
    scenes.push(currentScene);
  }

  return scenes;
}

// ── Duration Calculator ────────────────────────────────────────
// Source: guia_referencia_rapida_notebooklm.md, Tabla 7 (Regla 2)
// 1 page = 1 minute
export function estimateDurationFromText(text: string): {
  pages: number;
  minutes: number;
} {
  const wordCount = text.split(/\s+/).length;
  // Standard: ~175 words per script page
  const pages = Math.round(wordCount / 175);
  return { pages, minutes: pages };
}

export function getTotalDuration(guion: GuionJSON): number {
  return guion.scenes.reduce((total, scene) => total + scene.durationSeconds, 0);
}

// ── Character Extractor ────────────────────────────────────────
export function extractCharacters(guion: GuionJSON): string[] {
  const chars = new Set<string>();
  guion.scenes.forEach((scene) => {
    scene.characters.forEach((c) => chars.add(c));
    scene.dialogue?.forEach((d) => chars.add(d.character));
  });
  return Array.from(chars).sort();
}

// ── Beat Color Coding ──────────────────────────────────────────
// Source: metaprompt_maestro_antigravity.md, PARTE 3.2 + 6.1
export function getBeatColor(beatType: string): string {
  const colors: Record<string, string> = {
    Acción: "#3B82F6",      // Blue
    Diálogo: "#10B981",     // Green
    Transición: "#8B5CF6",  // Purple
    "Punto de Giro": "#EF4444", // Red
  };
  return colors[beatType] || "#6B7280"; // Gray as fallback
}

export function getActColor(act: string): string {
  const colors: Record<string, string> = {
    "Acto 1 (Inicio)": "#1E40AF",   // Dark Blue
    "Acto 2 (Nudo)": "#065F46",  // Dark Green
    "Acto 3 (Desenlace)": "#7F1D1D",   // Dark Red
  };
  return colors[act] || "#374151";
}

// ── Scene to Full Text ─────────────────────────────────────────
export function sceneToText(scene: Scene): string {
  const lines: string[] = [];
  lines.push(scene.slugline);
  lines.push("");
  if (scene.action) lines.push(scene.action);
  lines.push("");
  scene.dialogue?.forEach((d) => {
    lines.push(d.character);
    if (d.parenthetical) lines.push(d.parenthetical);
    lines.push(d.text);
    lines.push("");
  });
  return lines.join("\n");
}

// ── Utility ────────────────────────────────────────────────────
function wordWrap(text: string, maxLen: number): string[] {
  if (!text) return [];
  const words = text.split(" ");
  const lines: string[] = [];
  let current = "";

  words.forEach((word) => {
    if ((current + " " + word).trim().length <= maxLen) {
      current = (current + " " + word).trim();
    } else {
      if (current) lines.push(current);
      current = word;
    }
  });

  if (current) lines.push(current);
  return lines;
}
